# APP CONFIG
spring.application.name=securitymonitor
server.port=8080

# DATABASE CONFIG
spring.datasource.url=jdbc:postgresql://localhost:5432/security_monitoring_db
spring.datasource.username=postgres
spring.datasource.password=postgres123

# JPA / HIBERNATE CONFIG
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SQL INIT (FOR schema.sql)
spring.sql.init.mode=always

# SWAGGER CONFIG
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.packages-to-scan=com.harshit.securitymonitor

# ACTUATOR (OPTIONAL DEBUG)
management.endpoints.web.exposure.include=*

# SECURITY (DISABLE DEFAULT LOGIN)
spring.security.user.name=admin
spring.security.user.password=admin

# JWT CONFIG
jwt.secret=9a4f2c8d3b7a1e6f4d8c2b9a1f3e7d5b6c8a4f2d1e3b7a9f6d8c2b4a1f3e7d5b